<script setup>
import { ref } from 'vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';

const props = defineProps({ google: { type: Object, required: true } });
const activeTab = ref('google');
const toggleCalendarForm = useForm({ enabled: props.google.enabled });
const toggleLoginForm = useForm({ enabled: props.google.login_enabled });
const credentials = useForm({ client_id: props.google.client_id || '', client_secret: '', redirect_uris: [...(props.google.redirect_uris || [])] });

function toggleCalendar() { toggleCalendarForm.enabled = !toggleCalendarForm.enabled; toggleCalendarForm.patch(route('admin.integrations.google.toggle'), { preserveScroll: true }); }
function toggleLogin() { toggleLoginForm.enabled = !toggleLoginForm.enabled; toggleLoginForm.patch(route('admin.integrations.google-login.toggle'), { preserveScroll: true }); }
function addRedirectUri() { credentials.redirect_uris.push(''); }
function removeRedirectUri(index) { if (credentials.redirect_uris.length > 1) credentials.redirect_uris.splice(index, 1); }
function saveCredentials() { credentials.patch(route('admin.integrations.google.credentials'), { preserveScroll: true, onSuccess: () => credentials.reset('client_secret') }); }
</script>

<template>
    <Head title="Integrações — Administração" />
    <AuthenticatedLayout>
        <div class="max-w-5xl">
            <div class="border-b border-slate-200 pb-6"><nav class="mb-1 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-slate-400"><Link :href="route('admin.dashboard')" class="hover:text-slate-700">Administração</Link><span>/</span><span class="text-slate-600">Integrações</span></nav><h1 class="text-2xl font-bold tracking-tight text-slate-900">Integrações</h1><p class="mt-1 text-sm text-slate-500">Gerencie os serviços externos disponíveis no MeuHub.</p></div>
            <nav class="mt-6 flex flex-wrap gap-2 border-b border-slate-200"><button @click="activeTab = 'google'" :class="activeTab === 'google' ? 'border-indigo-600 text-indigo-700' : 'border-transparent text-slate-500 hover:text-slate-800'" class="border-b-2 px-4 py-3 text-sm font-semibold">Google</button><button @click="activeTab = 'n8n'" :class="activeTab === 'n8n' ? 'border-indigo-600 text-indigo-700' : 'border-transparent text-slate-500 hover:text-slate-800'" class="border-b-2 px-4 py-3 text-sm font-semibold">N8N</button></nav>
            <div v-if="activeTab === 'google'" class="mt-8"><section class="space-y-4">
                <div v-if="!google.configured" class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800" role="alert">As credenciais OAuth ainda não foram configuradas. Cadastre o Client ID, o Client Secret e as URLs de redirecionamento abaixo para liberar o login com o Google e a conexão com a Google Agenda.</div>
                <article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div class="flex gap-4"><div class="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50 text-2xl font-bold text-blue-600">G</div><div><h2 class="font-semibold text-slate-900">Login com Google</h2><p class="mt-1 text-sm text-slate-500">Permite que usuários entrem no MeuHub usando a conta Google.</p><p class="mt-2 text-xs text-slate-400">{{ google.google_registered_users }} cadastros realizados com o Google.</p></div></div><span :class="google.login_enabled ? 'bg-emerald-50 text-emerald-700 before:bg-emerald-500' : 'bg-slate-100 text-slate-600 before:bg-slate-400'" class="inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold before:mr-1.5 before:h-1.5 before:w-1.5 before:rounded-full before:content-['']">{{ google.login_enabled ? 'Ativo' : 'Inativo' }}</span></div><div class="mt-5"><button @click="toggleLogin" class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white">{{ google.login_enabled ? 'Desabilitar login com Google' : 'Habilitar login com Google' }}</button><p class="mt-3 text-xs leading-5 text-slate-500">O botão de login aparece quando a opção está habilitada. Se as credenciais faltarem, o sistema exibirá um alerta ao usuário.</p></div></article>
                <article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div class="flex gap-4"><div class="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-50 text-2xl font-bold text-indigo-600">G</div><div><h2 class="font-semibold text-slate-900">Google Agenda</h2><p class="mt-1 text-sm text-slate-500">Disponibiliza conexão e sincronização com a agenda do Google.</p><p class="mt-2 text-xs text-slate-400">{{ google.connected_users }} usuários conectados</p></div></div><span :class="google.enabled ? 'bg-emerald-50 text-emerald-700 before:bg-emerald-500' : 'bg-slate-100 text-slate-600 before:bg-slate-400'" class="inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold before:mr-1.5 before:h-1.5 before:w-1.5 before:rounded-full before:content-['']">{{ google.enabled ? 'Ativa' : 'Inativa' }}</span></div><div class="mt-5 flex flex-wrap items-center gap-3"><button @click="toggleCalendar" class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white">{{ google.enabled ? 'Desabilitar integração' : 'Habilitar integração' }}</button></div><p class="mt-3 text-xs leading-5 text-slate-500">A opção de integração aparece para o usuário quando esta opção está habilitada. Se as credenciais faltarem, o sistema exibirá uma alerta ao usuário.</p><p v-if="google.configured" class="mt-2 text-xs leading-5 text-emerald-700">As credenciais OAuth estão configuradas e prontas para uso quando a integração estiver habilitada.</p></article>
            </section><section class="mt-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><form @submit.prevent="saveCredentials" class="space-y-5"><div><h2 class="font-semibold text-slate-900">Credenciais OAuth compartilhadas</h2><p class="mt-1 text-xs leading-5 text-slate-500">O Client ID e o Client Secret são usados pelo login e pela Agenda. O segredo é armazenado criptografado e nunca é exibido novamente.</p></div><div><label class="text-xs font-semibold text-slate-600">Client ID</label><input v-model="credentials.client_id" required class="mt-1 w-full rounded-xl border-slate-300 text-sm" placeholder="Seu Client ID do Google Cloud" /></div><div><label class="text-xs font-semibold text-slate-600">Client Secret <span v-if="google.has_secret" class="font-normal text-emerald-600">(já configurado)</span></label><input v-model="credentials.client_secret" type="password" class="mt-1 w-full rounded-xl border-slate-300 text-sm" placeholder="Informe somente para substituir" /></div><div><div class="flex items-center justify-between"><label class="text-xs font-semibold text-slate-600">URLs de redirecionamento autorizadas</label><button type="button" @click="addRedirectUri" class="inline-flex items-center gap-1 rounded-lg bg-slate-100 px-2.5 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-200"><span class="text-base leading-none">+</span> Adicionar</button></div><p class="mt-1 text-xs text-slate-500">Cadastre todas as URLs também no Google Cloud Console.</p><div v-for="(uri, index) in credentials.redirect_uris" :key="index" class="mt-2 flex gap-2"><input v-model="credentials.redirect_uris[index]" type="url" required class="min-w-0 flex-1 rounded-xl border-slate-300 text-sm" placeholder="https://seu-dominio/configuracoes/integracoes/google/callback" /><button v-if="credentials.redirect_uris.length > 1" type="button" @click="removeRedirectUri(index)" class="rounded-xl px-3 text-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600" title="Remover URL">×</button></div></div><div class="flex justify-end"><button :disabled="credentials.processing" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">Salvar configurações</button></div></form></section></div>
            <section v-else class="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><div class="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-slate-100 text-slate-400"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v18M3 12h18" /></svg></div><h2 class="mt-4 font-semibold text-slate-800">N8N</h2><p class="mt-1 text-sm text-slate-500">A integração com N8N estará disponível em breve.</p></section>
        </div>
    </AuthenticatedLayout>
</template>
